site_name: Artresearch.net Data Model
site_url: https://docs.artresearch.net
theme:
  name: material
  features:
  - navigation.expand
nav:
  - Home: 'index.md'
  - Photo Archives: 'PhotoArchives.md'
  - Authorities: 'Authorities.md'
  - Data Models:
    - 'Instructions': 'Instructions.md' 
    - 'Artwork / Monument': 'Artwork.md'
    - 'Photograph': 'Photo.md'
    - 'Artist': 'Artist.md'
    - 'Person': 'Person.md'
    - 'Photographer': 'Photographer.md'
    - 'Repository': 'Institution.md'
    - 'Place': 'Place.md'

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
extra_css: 
  - extra.css

 
