name: Deploy MkDocs Site

on:
  push:
    branches:
      - master  # Make sure this is your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material

    - name: Build the MkDocs Site
      run: mkdocs build

    - name: Copy CNAME file
      run: cp CNAME site/CNAME

    - name: Deploy to GitHub Pages
      run: mkdocs gh-deploy --force
